#!/usr/bin/env python3
"""Generate game/config/rom/*.yaml from the asset package (adds MPF's config_version header).

The asset package's YAML has no "#config_version=6" first line, which MPF requires. These files are
generated, not edited: re-run after every asset sync (setup_workspace.sh and the tests do it).

It also writes rom/proc_numbers.yaml, the P-ROC addresses of every switch, coil and light (hw_proc.yaml),
from the SAM numbers in rom/*.yaml and hardware.yaml, in the strings libpinproc's decode() takes for
driverboards sternSAM (PRDecode in libpinproc src/pinproc.cpp):
- matrix switch n (1-64) -> "Snn", dedicated switch "D<n>" (1-24) -> "SD<n>"
- coil/flasher n (1-32) -> "Cnn"; 33-40 are latched from the IO board's aux bus, which the P-ROC does
  not drive as drivers, so they stay on the virtual platform
- lamp n (1-80) -> "Lnn"; the ramp light tubes ("aux_strobe_...") are aux bus outputs too: virtual
  platform, driven by tron/proc_hardware.py when enabled
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC = os.path.join(ROOT, "assets", "mpf_package", "config")
DST = os.path.join(ROOT, "game", "config", "rom")
FILES = ["switches.yaml", "coils.yaml", "lights.yaml", "settings.yaml"]
CONFIG = os.path.join(ROOT, "game", "config")
PROC_SOURCES = ["rom/switches.yaml", "rom/coils.yaml", "rom/lights.yaml", "hardware.yaml"]


def _write(path, out):
    if not os.path.exists(path) or open(path).read() != out:
        with open(path, "w") as f:
            f.write(out)


def proc_number(section, number):
    """SAM number -> (libpinproc number string, None) or (None, reason it stays virtual)."""
    text = str(number).strip()
    if section == "switches":
        m = re.fullmatch(r"D(\d+)", text)
        if m and 1 <= int(m.group(1)) <= 24:
            return "SD{}".format(int(m.group(1))), None
        if text.isdigit() and 1 <= int(text) <= 64:
            return "S{:02d}".format(int(text)), None
    elif section == "coils":
        if text.isdigit() and 1 <= int(text) <= 32:
            return "C{:02d}".format(int(text)), None
        if text.isdigit() and 33 <= int(text) <= 40:
            return None, "aux bus latch output, not a P-ROC driver"
    elif section == "lights":
        if text.isdigit() and 1 <= int(text) <= 80:
            return "L{:02d}".format(int(text)), None
        if text.startswith("aux_strobe_"):
            return None, "aux bus RGB tube, driven by tron/proc_hardware.py"
    raise ValueError("{} number {!r} is not a SAM number".format(section, number))


def gen_proc_numbers():
    from ruamel.yaml import YAML        # MPF's YAML library (the .venv has no PyYAML)
    yaml = YAML(typ="safe")
    lines = ["#config_version=6",
             "# GENERATED by scripts/gen_config.py from {}:".format(", ".join(PROC_SOURCES)),
             "# P-ROC (driverboards sternSAM) numbers for every switch, coil and light. Included by hw_proc.yaml."]
    for section in ("switches", "coils", "lights"):
        entries = []
        for source in PROC_SOURCES:
            with open(os.path.join(CONFIG, source)) as f:
                data = yaml.load(f) or {}
            for name, cfg in (data.get(section) or {}).items():
                if cfg and "number" in cfg:
                    entries.append((name, cfg["number"]))
        lines.append("{}:".format(section))
        for name, number in entries:
            proc, reason = proc_number(section, number)
            lines.append("  {}:".format(name))
            if proc:
                lines.append("    number: {}   # SAM {}".format(proc, number))
            else:
                lines.append("    platform: virtual   # SAM {}: {}".format(number, reason))
    _write(os.path.join(DST, "proc_numbers.yaml"), "\n".join(lines) + "\n")


def main():
    os.makedirs(DST, exist_ok=True)
    for name in FILES:
        with open(os.path.join(SRC, name)) as f:
            body = f.read()
        # MPF 0.80 has no "flashers:" section; flashers are plain coils there.
        body = body.replace("\nflashers:\n", "\n# (flashers, as coils for MPF 0.80)\n")
        # the package writes the setting group as "setting_type"; MPF 0.80's settings spec calls it "settingType"
        body = body.replace("    setting_type: ", "    settingType: ")
        out = "#config_version=6\n# GENERATED from assets/mpf_package/config/{} by scripts/gen_config.py\n{}".format(
            name, body)
        _write(os.path.join(DST, name), out)
    gen_proc_numbers()
    return 0


if __name__ == "__main__":
    sys.exit(main())
